# Generated by Django 4.0.3 on 2022-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato_dev', '0002_category_remove_news_category_news_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
